import CameraIcon from "./Camera";
import CameraColoredIcon from "./CameraColored";
import HomeIcon from "./Home";
import SettingsIcon from "./Settings";
import UsersIcon from "./Users";
import SendMessageIcon from "./SendMessage";
import ClockIcon from "./Clock";
import UnionIcon from "./Union";
import BackIcon from "./Back";
import OnlineIcon from "./OnlineIcon";
import ChamXsIcon from "./ChamXs";
import AddPeople from "./AddPeople";
import RecordIcon from "./Record";
import CameraRecordIcon from "./CameraRecord";
import SearchIcon from "./Search";
import DownArrowIcon from "./DownArrow"
import MoreIcon from "./More";
import VectorBackIcon from "./VectorBack";
import ModalCloseIcon from "./ModalClose";
import ChangeBackgroundIcon from "./ChangeBackground";
import AttendeesIcon from "./Attendees";
import RaiseHandIcon from './RaiseHand'
import RedHeartIcon from "./RedHeart";
import SurprisedFaceIcon from "./SurprisedFace";
import LaughSmileyIcon from "./LaughSmiley";
import ClappingHandIcon from "./ClappingHand";
import ThumbsUpIcon from "./ThumbsUp";
import MicrophoneIcon from "./Microphone"
import MessageIcon from "./Message";
import MessageRedIcon from "./MessageRed";
import ShareScreenIcon from "./ShareScreen";
import ShareScreenRedIcon from "./ShareScreenRed";
import EndCallIcon from "./EndCall";
import CheckIcon from "./Check";
import VideoInputIcon from "./VideoInput";
import AttendeesButtontIcon from "./AttendeesButton";
import EndCallDesktopIcon from "./EndCallDesktop";
import TripleDotIcon from "./TripleDot";
export { CameraIcon, SettingsIcon, RecordIcon, OnlineIcon, HomeIcon, UsersIcon, SendMessageIcon, ClockIcon, UnionIcon, BackIcon, CameraColoredIcon, ChamXsIcon, AddPeople, CameraRecordIcon, SearchIcon, DownArrowIcon, MoreIcon, VectorBackIcon, ModalCloseIcon, ChangeBackgroundIcon, AttendeesIcon, RaiseHandIcon, RedHeartIcon, SurprisedFaceIcon, LaughSmileyIcon, ClappingHandIcon, ThumbsUpIcon, MicrophoneIcon, MessageIcon, MessageRedIcon, ShareScreenIcon, ShareScreenRedIcon, EndCallIcon, CheckIcon, VideoInputIcon, AttendeesButtontIcon, EndCallDesktopIcon, TripleDotIcon }